### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by janmaier2277** [TheSpaghettiDetective/tsd-moonraker#12]
Thanks for your work, im running it and having 0 issues!

Not really an issue, but i thought i would bring it up anyway: 
Right now tsd-moonraker doesnt seem to be published under a specific license. If this is not an oversight and intended im sorry, otherwise Id like to suggest to put it under AGPL (just like TSD itself) if possible. 
Thanks a lot and keep up the good work!

**Comment by encetamasb** [comment]
@janmaier2277 Added missing license file. Thanks!
