### ISSUE TITLE
Flip camera horizontally/vertically

### ISSUE THREAD

**Issue by 1n9i9c7om** [TheSpaghettiDetective/tsd-moonraker#17]
Hi,

I was wondering if there's any way to flip the camera horizontally & vertically. My camera is mounted upside down and when I used OctoPrint, the plugin would automatically detect that I had the camera flipped and would apply the same to the TSD stream.

Now that I switched to Klipper & Moonraker, I noticed that the Moonraker version of TSD does not do that and does not seem to offer this functionality in the configuration (yet?). However, I also understand that this is an early version of the plugin, so I'm not too surprised :)
Is this planned in the future? Does the TSD AI still work properly with an upside-down image?

**Comment by encetamasb** [comment]
Thanks for bringing this up. 

I can see 4 possible configuration keys we can add, TSD server can understand the following: flipV, flipH, rotate90, streamRatio.

Let's say, it's planned, and probably sooner, than later.
